Traceback (most recent call last):
  File "/home/runner/.local/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/runner/.local/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/runner/.local/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/runner/.local/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/runner/.local/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/runner/.local/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/runner/.local/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
df_electivas = utils.curar_data(utils.generar_subdf_materias_electivas(df))

G_electivas = nx.from_pandas_edgelist(df_electivas, 
                            source='Padron_x', 
                            target='Padron_y', 
                            edge_attr='cant_materias_similares',
                            create_using=nx.Graph())

print(G_electivas)
print(f"""
Red FIUBA-Map
  El diÃ¡metro de la red: {nx.diameter(G_electivas)}
  El grado promedio de la red: {sum([n[1] for n in G_electivas.degree()]) / len(G_electivas):.2f}
  La distancia promedio de la red: {nx.average_shortest_path_length(G_electivas)}
  Clustering promedio: {"%3.4f"%nx.average_clustering(G_electivas)}
  Puentes globales: {list(nx.bridges(G_electivas))}
  {"Es conexa" if nx.is_connected(G_electivas) else "No es conexa"}
""")
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
Cell [0;32mIn [8], line 1[0m
[0;32m----> 1[0m df_electivas [38;5;241m=[39m utils[38;5;241m.[39mcurar_data(utils[38;5;241m.[39mgenerar_subdf_materias_electivas(df))
[1;32m      3[0m G_electivas [38;5;241m=[39m nx[38;5;241m.[39mfrom_pandas_edgelist(df_electivas, 
[1;32m      4[0m                             source[38;5;241m=[39m[38;5;124m'[39m[38;5;124mPadron_x[39m[38;5;124m'[39m, 
[1;32m      5[0m                             target[38;5;241m=[39m[38;5;124m'[39m[38;5;124mPadron_y[39m[38;5;124m'[39m, 
[1;32m      6[0m                             edge_attr[38;5;241m=[39m[38;5;124m'[39m[38;5;124mcant_materias_similares[39m[38;5;124m'[39m,
[1;32m      7[0m                             create_using[38;5;241m=[39mnx[38;5;241m.[39mGraph())
[1;32m      9[0m [38;5;28mprint[39m(G_electivas)

[0;31mAttributeError[0m: module 'utils' has no attribute 'curar_data'
AttributeError: module 'utils' has no attribute 'curar_data'

